# -*- coding: utf-8 -*-
"""IMDB RATING BEAUTIFULSOUP PORJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiknMgoUq0Rw6WRZ8ApXr3LMmIZqxq14
"""

#IMPORTING THE LIBRARIES
from bs4 import BeautifulSoup
import requests
import openpyxl

#IMPORTING THE EXCEL LIBRARY
excel = openpyxl.Workbook()

#TO WORK IN ACTIVE SHEET
sheet = excel.active

#CHANGING THE EXCEL SHEET NAME
sheet.title = 'Top Rated Movies'
print(excel.sheetnames)

#EXCEL COLUMN NAME
sheet.append(['Movies Rank','Movies Name','Year of Release','IMDB Rating'])

#IMPORT THE SOURCE WEBSITE LINK
source = requests.get('https://www.imdb.com/chart/top/')
print(source)

#CHECKING FOR THE WRONG WEBSITES
  source.raise_for_status

#CHECKING TEXT IN HTML
  soup = BeautifulSoup(source.text,'html.parser')
  print(soup)

#CHECKING THE ALL MOVIE
 movies = soup.find('tbody',class_="lister-list").find_all('tr')

#For Printing One Value
for movie in movies:

        #name of the Movies
        name = movie.find('td',class_="titleColumn").a.text
        rank= movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
        rank= movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
        year = movie.find('td',class_="titleColumn").span.text.strip('()') #strip are used to remove ()
        rating = movie.find('td',class_="ratingColumn imdbRating").strong.text
        print(rank,name, year,rating)
        break

#FOR PRINTING ALL VALUES
for movie in movies:

        #name of the Movies
        name = movie.find('td',class_="titleColumn").a.text
        rank= movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
        rank= movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
        year = movie.find('td',class_="titleColumn").span.text.strip('()') #strip are used to remove ()
        rating = movie.find('td',class_="ratingColumn imdbRating").strong.text
        print(rank,name, year,rating)

sheet.append([rank,name, year,rating])

#TO SAVE FILE IN EXCEL
excel.save('IMBD Movie Rating.xlsx')

excel

